### PR TITLE
Changed date field from int64 to time.Time to fix the parsing error.

### PR DESCRIPTION
**Pull request by iamsumit**
Related issue: https://github.com/go-playground/webhooks/issues/47

This PR fixes the parse error for installation repositories event for date fields by using time.Time instead of int64 type.

### CODE REVIEW

**Comment by deankarn** [comment]
@iamsumit would you be able to update the tests to use the new GitHub output? the tests seem to be failing.

**Comment by iamsumit** [comment]
> @iamsumit would you be able to update the tests to use the new GitHub output? the tests seem to be failing.

I fixed the tests. However, the `integration_installation` and `integration_installation_repo` events were failing due to the same issue. There is no such events listed on the [github docs](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads).

**Comment by alehechka** [comment]
Running into this same issue. I was able to replace the dependency with your fork, but wondering what the approval process is to get this merged in?

**Review by deankarn — APPROVED** [review]
LGTM

**Pull request merged**
