### PR TITLE
Modify Gitlab Job and Pipeline events 

### PR DESCRIPTION
**Pull request by shaheed121**
Modify Pipeline events and Job events payload as per https://docs.gitlab.com/ee/user/project/integrations/webhooks.html

### CODE REVIEW

**Comment by shaheed121** [comment]
@Toshik1978 @deankarn Could you all take a look at this please?

**Comment by Toshik1978** [comment]
@shaheed121 will review this week!

**Comment by Toshik1978** [comment]
@shaheed121 interesting situation. Commonly your changes are backward incompatible. The question is how current code can be used at all... If smbd. by some reasons used it (it should not work, but...), than it's a problem )

**Comment by shaheed121** [comment]
Changes to job events was merged in Gitlab on [Aug 29, 2019](https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/32390).  Also, changes to pipeline events to use `builds` instead of `jobs` happened on [May 23, 2019](https://gitlab.com/gitlab-org/gitlab-foss/-/commit/2f3263961e7f42e0af2e94752a535a4bd59c7fc1). So it hasn't been working for a while. I have made more additions and removed deprecated keys that are not being in use.

@Toshik1978 So could you please release a major version release of the library with note on backward incompatible change for Gitlab?

**Comment by Toshik1978** [comment]
@shaheed121 I'm almost agree with you. We already have several PRs with breaking changes. But I want to sync it with @deankarn. Dean, what do you think? I'm ready to release v6 commonly

**Comment by shaheed121** [comment]
@Toshik1978 @deankarn Do you think you can provide some love to this? :)

**Review by deankarn — APPROVED** [review]
LGTM

@Toshik1978 yes by all means if there are breaking changes let's release a new version :)
If you could try to get multiple breaking change PR's merged into the same release, that'd be ideal.

**Comment by Toshik1978** [comment]
@deankarn yeap, definitely will review all latest PRs with incompatible changes and release at once!
@shaheed121 I'll try to release new major version this week.

**Pull request merged**
