### PR TITLE
Added runner to gitlab

### PR DESCRIPTION
**Pull request by xackery**
this has been changed on CE, I imagine all versions may be affected.
It has not yet been heavily tested, I ended up designing an alternative, hard coded one, but figured i'd PR the items to be considered that I worked on.

### CODE REVIEW

**Comment by joeybloggs** [comment]
LGTM

can I asked where you found the schema for the `runner`? I wasn't;t able to find the docs on it

**Comment by xackery** [comment]
I just took your example code, decoded/printed the body before your hook.Parse, then mocked up the structs needed to satisfy. I couldn't find documentation yet either of the change.. I just knew that your latest v5 branch was erroring on runner before I applied this fix.

**Comment by joeybloggs** [comment]
@xackery thanks for the details

I'm going to merge this :)

**Comment by xackery** [comment]
As a confirmation @joeybloggs 
https://gitlab.com/gitlab-org/gitlab-ce/issues/53121#note_111781800 
```
"runner":{
            "id":380987,
            "description":"shared-runners-manager-6.gitlab.com",
            "active":true,
            "is_shared":true
         },
```

**Pull request merged**
