### PR TITLE
feat: add Azure DevOps git push event

### PR DESCRIPTION
**Pull request by robinlieb**
Added Azure DevOps code pushed event based on following definition: https://learn.microsoft.com/en-us/azure/devops/service-hooks/events?view=azure-devops#code-pushed

### CODE REVIEW

**Review by gregorsarnow — APPROVED** [review]
lgtm

**Review by Toshik1978 — APPROVED** [review]
LGTM

**Comment by alexmt** [comment]
Thank you @robinlieb ! Do you have an ETA when these changes will be released?

**Comment by robinlieb** [comment]
@alexmt just released with version 6.3.0.

**Pull request merged**
