### PR TITLE
Adds CodeScanningAlertEvent

### PR DESCRIPTION
**Pull request by ffeldmann**
Adds the code_scanning_alert event from GitHub to GitHub.go web hook base.
Reference to Github docu: https://docs.github.com/en/webhooks/webhook-events-and-payloads#code_scanning_alert

### CODE REVIEW

**Comment by abhijith-darshan** [comment]
any news on merging this PR? As it is a good use case to consume GitHub Advanced Security events via webhooks.

**Comment by ffeldmann** [comment]
@ammario is this project still maintained?

**Comment by ammario** [comment]
Not sure. I'm not the maintainer.

cc @robinlieb merged in my change.

**Review by robinlieb — APPROVED** [review]

**Comment by robinlieb** [comment]
@ffeldmann Thanks!

**Pull request merged**
