### PR TITLE
fix: Installation Struct Missing for CommitCommentPayload, IssueCommentPayload and IssuesPayload

### PR DESCRIPTION
**Pull request by Fish-Nullify**
This pull request fixes issue https://github.com/go-playground/webhooks/issues/177

### CODE REVIEW

**Comment by robinlieb** [comment]
Hi @Fish-Nullify, 
Since this field is optional on the mentioned payloads, would it make sense to treat the installation struct accordingly? Something like:
```
Installation *struct {
	ID int64 `json:"id"`
} `json:"installation,omitempty"`
```
@deankarn do you have an opinion on that?

**Comment by Fish-Nullify** [comment]
Hi @robinlieb, 

Thanks for the suggestion and I have provided an update to the installation structs for the specified payloads. I can easily revert this if necessary.

**Comment by deankarn** [comment]
@robinlieb I agree, if it’s optional then let’s make it a pointer.

@Fish-Nullify omitempty only works for Serialization in Go and not Deserialization.

**Comment by robinlieb** [comment]
@Fish-Nullify could you them please make the installation struct a pointer and remove the omitempty? Like:
```
Installation *struct {
	ID int64 `json:"id"`
} `json:"installation"`
```

**Review by robinlieb — APPROVED** [review]

**Pull request merged**
